#!/bin/bash
echo $(echo $WATER | tr 'water' '01234') $(echo $STIR | tr 'stir' '01234') | xargs printf "%d\n" | awk '{ sum += $1 } END { print sum }' | fold -w1 | tr '0123456789' 'cbadefihgj' | tr -d '\n'
